apiVersion: v1
kind: Service
metadata:
  name: debezium
  labels:
    name: debezium
  namespace: debezium
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: debezium