apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: debezium-gke
  labels:
    name: debezium
  namespace: debezium
spec:
  replicas: 1
  serviceName: debezium
  selector:
    matchLabels:
      name: debezium
  template:
    metadata:
      labels:
        name: debezium
        version: v1
    spec:
      serviceAccountName: <Service Name Created while creating Cluster>
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: debezium
          image: debezium/server:1.7.0.Final
          volumeMounts:
            - name: debezium-config-volume
              mountPath: /debezium/conf
            - name: debezium-data-volume
              mountPath: /debezium/data
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=<ConnectionName from CloudSQL Page>=tcp:<Port>"
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: debezium-config-volume
          configMap:
            name: debezium
  volumeClaimTemplates:
    - metadata:
        name: debezium-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gb